[tool.bumpver]
current_version = "0.5.0-alpha0"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"setup.py" = ['version="{version}"']
"src/dmme/__init__.py" = ['__version__ = "{version}"']
"docs/source/conf.py" = ['release = "{version}"']
